name: random_selection_text_animation
description: Animation of random picking characters in a Text widget
version: 1.0.0
repository: https://github.com/eeeedgar/random_selection_text_animation

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
